### ISSUE TITLE
Modification of Object.prototype is dangerous and breaks other code

### ISSUE THREAD

**Issue by ddurschlag6river** [samchon/tstl#12]
**Summary**:
  - **TSTL Version**: 1.7.11
  - **Expected behavior**: Library does not modify Object.prototype; other libraries and code work normally
  - **Actual behavior**
Library does modify Object.prototype, breaking other libraries and code

**Code occuring the bug**: 
```typescript
import {base} from 'tstl';
import * as sinon from 'sinon';
const tree = new (base.Container as any)();
sinon.createStubInstance(Object); // sinon blows up
```

**Comment by samchon** [comment]
TSTL defines a new method `__get_m_iUID` on the `Object.prototype`.

Of course, I know that modifying `Object.prototype` is dangerous, however, it was an inevitable problem to make something possible; **using an Object as a mapped key**. To use an Object as a mapped key, both of them should be possible.

  - Objects should be hashed: `std.hash`
  - Objects should be compared: `std.less`

The standard way to make them possible is to using address (convert the pointer type to unsigned long long and hash or compare the value) of Objects. However, Objects in JavaScript do not provide their own address, so utilizing the standard way in JavaScript is not possible.

The alternative way to make them possible is to issuing an UID to each Object. Whenever hashing and comparing an Object, the UID can be used instead of the address. Of course, to issue the UID, I couldn't avoid implementing the `Object.prototype.__get_m_iUID` method.

```typescript
import * as std from "tstl";

let hash_map: std.HashMap<Object, string>;
let tree_map: std.TreeMap<Object, number>;
```

Thanks for your issue makes me reviewing base code of TSTL. If you have an innovative solution that can avoid touching the `Object.prototype`, then please tell me the solution. If not, I'm sorry for writing such unfortunate comment saying "impossible".

**Comment by ddurschlag6river** [comment]
I'd recommend two changes:
1) Don't modify object.prototype. Instead, have a function internal to tstl that performs this operation on a target object. In other words, `hash(obj)` instead of `obj.hash()`.
2) When using `defineProperty` to assign an object an id, do so with writable and configurable set to true. This will allow the property to be modified or removed, if necessary (though of course with the caveat that it will be "lost" in hash tables already containing it).

This should solve the vast majority of cases.

In case it's of interest, I moved to jstreemap for my immediate requirement. It has a bug involving iterators shifting around as trees are modified that I had to work around, but it doesn't modify object.prototype. It also was, in my case, many times faster.

**Comment by samchon** [comment]
## 1. Not `obj.hash()` but `std.hash(obj)`
  - http://samchon.github.io/tstl/api/modules/std.html#hash
  - https://github.com/samchon/tstl/blob/v1.8/src/functional/hash.ts

Only a function modifying the `Object.prototype` is `Object.prototype.__get_m_iUID()`.


## 2. Instead of `defineProperty`
Chaning `Object.prototype` is inevitable problem in my **TSTL**. So I tried an alternative implementation on a new branch. It does not implement the `Object.prototype.__get_m_iUID()` by using the `defineProperty`, but declaring function directly.

  - https://github.com/samchon/tstl/blob/v1.8-prototype/src/functional/hash.ts#L112-L127
  - `npm install --save tstl@next`

The new implementation also modifies the `Object.prototype`, however, it doesn't occur error when calling the `sinon.createStubInstance(Object)`. It seems better?

**Comment by samchon** [comment]
Well, reading your issue carefully, I've got the solution. 

To keep the uniqueness of UID, I should use the global variable. Instead of defining a dangerous method in the `Object.prototype`, I could define a static function using the global sequence number.

```typescript
export function get_uid(obj: any): number
{
	let root: IGlobal = (window ? window : global) as any;
	if (root.__s_iUID === undefined)
		root.__s_iUID = 0;

	if (obj.hasOwnProperty("__m_iUID") === false)
	{
		var uid: number = ++root.__s_iUID;
		Object.defineProperty(obj, "__m_iUID", 
		{
			get: function (): number
			{
				return uid;
			}
		});
	}
	return obj.__m_iUID;
}

export interface IGlobal
{
	__s_iUID?: number;
}
```

Thanks for your suggestion.

**Comment by ddurschlag6river** [comment]
I definitely think you're headed in the right direction. Two questions:
1) Why use the global/window object instead of just having a variable in module scope closed over by the function? In other words, why not:
```
let __s_iUID = 0;
export function get_uid(obj: Object): number
{
	if (obj.hasOwnProperty("__m_iUID") === false)
	{
		var uid: number = ++__s_iUID ;
		Object.defineProperty(obj, "__m_iUID", 
		{
			get: function (): number
			{
				return uid;
			}
		});
	}
	return obj.__m_iUID;
}
```
2) Why not make the defined  property configurable and writable? That would let users of the library remove or overwrite it, which would make it compatible with sinon (as well as other reflection-like use cases).

Either way, definitely an improvement.

**Comment by samchon** [comment]
## 1. For the uniqueness
If I declare the `__s_iUID` not in the global scope, but in the module scope, then a confliction may occured when different versions of TSTL libraries are imported.

  - Library A imports TSTL v1.8
  - Library B imports TSTL v1.9
  - A project imports both A & B

In that case, `Object.__m_iUID` issued by the `__s_iUID` does not assure the uniqueness. It's the reason why I declared the variable not in the modular scope, but in the global scope.



## 2. `Object.__m_iUID` must be kept
`Object.__m_iUID` is the identifier who determines an object uniquely. 

If user modifies the identifier, then the rule whould be broken. When the `Object.__m_iUID` is modified by an user manually and the user is using a dictionary mapped by the `Object` like `std.HashMap<Object, ?>` or `std.TreeMap<Object, ?>`, it also causes the tragic accident.

**Comment by samchon** [comment]
This issue has applied.

https://github.com/samchon/tstl/blob/master/src/functional/uid.ts
